version: '3.1'

services:

  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: patata
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: patata
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  mysql_volume: