version: '3.1'

services:

  mysql:
    image: mysql:8.0.36
    restart: no
    environment:
      MYSQL_USER: alex
      MYSQL_PASSWORD: patata
      MYSQL_DATABASE: flask_db
      MYSQL_ROOT_PASSWORD: patata
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/flask
      - ./.env:/usr/src/flask/.env
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wannapop/static:/static
    depends_on:
      - flask

volumes:
  mysql_volume: